language: node_js
node_js:
  - "12.20.1"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before-script:
  - cd Frontend
  - npm install
  
script:
  - npm run lint
  - npm run test:headless
  - npm run build

notifications:
  slack:
    rooms:
      - sytwull:GgiUiOJJeifKY0uamYUGF1Zr#e03
      - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssecurestringidsuag34522irueg=" 
      on_success: always