name: Node.js CI
on: 
  branches-ignore:
    - "main"
jobs:
  Front-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    strategy:
      node-version: 12.x
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Frontend
        run: npm install

      - name: Frontend Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI