# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on: 
  push:
    branches: [ "desarrollo" ]
  pull_request:
    branches: [ "desarrollo" ]

jobs:
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        
      - name: Setup Backend
        run: cd ./Backend && npm install

      - name: Backend Test
        run: cd ./Backend && npm run test