name: Node.js CI Backend
on: 
  push:
    branches-ignore:
      - "main"
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest
    strategy:
      node-version: 12.x
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        
      - name: Setup Backend
        run: npm install

      - name: Backend Test
        run: npm run test